int mainMenu();
int choiceMainMenu();
int isChoiceMainMenuRight(const int);
int mainMenuGoTo(const int);
int difficultMenu();
int choiceDifficultMenu(int*);
int isChoiceDifficultMenuRight(const int);
int setDifficult(int*, const int);
int difficultMenuGoTo(const int, const int);
int levelMenu(const int);
int choiceLevelMenu(int*);
int isChoiceLevelMenuRight(const int);
int setLevel(int*, const int);
int levelMenuGoTo(const int, const int, const int);
int endingMenu(const int, const int, const int);
int choiceEndingMenu(int*, const int);
int isChoiceEndingMenuRight(const int, const int);
int endingMenuGoTo(const int, const int, const int, const int);
int endingMenuGoToIsGameWon(const int, const int, const int);
int endingMenuGoToIsNotGameWon(const int, const int, const int);
