int printTitle1(char*);
int printFirstProgramSeparator();
int printLastProgramSeparator();
int printFirstGameSeparator();
int printLastGameSeparator();
int printStars(int);
int printErrorWrongChoice(const int);
int printBeginingMessage();
int printEndingMessage();
int printErrorVariable(char*);
int printError(char*, int);
int printText(char*);
int printGameIndications(const int, const int, const int, const int);
int printScore(const int,const int,  const int, const int, const int);
int pause();
